json.id recipe.id
json.title recipe.title
json.chef recipe.chef
json.ingredients_list recipe.ingredients_list
json.directions recipe.directions
json.image_url recipe.image_url
json.friendly_prep_time recipe.friendly_prep_time
json.friendly_created_at recipe.friendly_created_at
json.updated_at recipe.updated_at